### ISSUE TITLE
Semgrep fails, fix coming

### ISSUE THREAD

**Issue by jmservera** [martinabrle/app-service-java-demo#13]
https://github.com/martinabrle/app-service-java-demo/blob/3851305adadab35d8c631196fa4699c0b027663c/.github/workflows/31-sast-semgrep.yml#L49

Coming fix: https://github.com/returntocorp/semgrep/issues/9091#issuecomment-1785241282

**Comment by aryx** [comment]
Why using the -o option? Why not simply using shell redirection with > results.sarif?
(just curious; I always wanted to remove this --output option which I find redundant with shell redirection but
maybe they are useful use-cases).

**Comment by TonyRL** [comment]
> Why using the -o option?

I guess it is because `--output` option is written in [Sample GitHub Actions configuration file](https://semgrep.dev/docs/semgrep-ci/sample-ci-configs/#sample-github-actions-configuration-file) (Alternate job that uploads findings to GitHub Advanced Security Dashboard)

**Comment by martinabrle** [comment]
@jmservera this action seems to be working now, can you please review? Thanks

**Comment by martinabrle** [comment]
It has been working for some time but I only look at the PRs in this repo today. Thanks :-)
